# Conda-only profile
cores: 24
jobs: 24
use-conda: true
use-singularity: false
printshellcmds: true
rerun-incomplete: true
restart-times: 0
keep-going: false
default-resources:
  - tmpdir="tmp"
  - mem_mb=4000
  - disk_mb=10000
