project: sv-neoantigen
threads: 20
tmpdir: tmp

samples: config/samples.tsv

references:
  bwa_index: resources/bwa_index
  star_index: resources/star_index
  kallisto_index: resources/kallisto_index/gencode.v47.transcripts.fa.gz
  gatk_dbsnp: resources/gatk/dbsnp_146.hg38.vcf.gz
  gatk_mils: resources/gatk/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
  gatk_fa: resources/bwa_index/hg38.fa
  gatk_dict: resources/bwa_index/hg38.fa.dict
  annotsv_data: resources/annotsv
  annotsv2pep_gtf: resources/annotsvtopep/gencode.v47.annotation.gtf
  annotsv2pep_id_map: resources/annotsvtopep/Seq_Ens.txt
  annotsv2pep_db: resources/annotsvtopep/gene_annotation.db
  netchop_home: resources/netchop_3_1
  netchop_bin: resources/netchop_3_1/bin/netChop
  netmhcpan_home: resources/netMHCpan-4.1/Linux_x86_64
  netmhcpan_bin: resources/netMHCpan-4.1/Linux_x86_64/bin/netMHCpan
  mhcflurry_model_tarball: resources/mhcflurry/models_class1_presentation.20200611.tar.bz2
  deepimmuno_home: resources/DeepImmuno


pairing:
  l041:
    tumor: l041_tumor
    normal: l041_normal
  l048:
    tumor: l048_tumor
    normal: l048_normal
  l052:
    tumor: l052_tumor
    normal: l052_normal
  l056:
    tumor: l056_tumor
    normal: l056_normal

params:
  bwa:
    threads: 12
    extra: ""
  samtools:
    sort_memory: "4G"
  gatk:
    java_options: "-Xmx16G"
    extra: ""
  star:
    threads: 12
    extra: "--outSAMtype BAM SortedByCoordinate"
  kallisto:
    strandedness: auto
    bootstrap: 0
    extra: ""
  hla:
    optitype_extra: ""
  svaba:
    threads: 12
    extra: ""  # user to fill actual command args
  annotsv:
    genome_build: GRCh38
    extra: ""
  neoantigen:
    flank_bp: 30
    peptide_lengths: [8, 9, 10, 11]
    min_tpm: 1.0
    min_vaf: 0.05
  netchop:
    threshold: 0.5
    n_term_min: 0.5
    c_term_min: 0.5
    internal_max: 0.5
    internal_count_max: 0
    extra: ""
  netmhc:
    peptide_lengths: [8, 9, 10, 11]
    rank_el_threshold: 2.0
    rank_ba_threshold: 2.0
    tmp_template: /tmp/netMHCpanXXXXXX
    extra: ""
  mhcflurry:
    docker_image: d365f27d62d2
    model_name: models_class1_presentation
    model_install_dir: ~/.local/share/mhcflurry
    model_check_subdir: 4/2.2.0/models_class1_presentation
    rank_threshold: 2.0
    extra: ""
  deepimmuno:
    python: python
    supported_lengths: [9, 10]
    threshold: 0.0
    extra: ""
  fragpipe:
    enzyme: unspecific
    fdr: 0.01
    extra: ""
  report:
    include_psms: true

final_outputs:
  - results/report/neoantigen_summary.tsv
  - results/report/neoantigen_report.xlsx
